isce-framework/nisarqa

.github/release.yml
Configure the automatically-generated release notes to exclude contributions from @dependabot and @pre-commit-ci.
https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options
=> Ignore contributions by bots in release notes

.github/CODEOWNERS
Later lines in a CODEOWNERS file take precedence over earlier lines. Previously, we put the two code owners on separate lines with identical wildcard patterns. This caused only the second code owner to be requested for review. This update puts both code owners on the same line, indicating co-ownership.
=> Fix precedence of code owners

src/nisarqa/utils/plotting.py
The new R4.0.4 sample products revealed a bug in QA. When QA re-wraps images by 7pi, the colorbar is not being generated correctly because the vmin and vmax are not being set. This impacts the PDF report and the browse images.
With the old R4.0.2 sample products, the unwrapped phase array crosses two intervals ( `[-7pi, 0)` and `[0, 7pi)`). and so it was being plotted like this:
With the new R4.0.4 sample products, the unwrapped phase array is contained within one interval ( `[0, 7pi)`). and so it was being plotted like this:
With the fix in this PR, we stretch the colorbar interval to plot correctly:
=> Bugfix: Set `vmin` and `vmax` when plotting InSAR images

src/nisarqa/__init__.py, src/nisarqa/parameters/nisar_params.py, src/nisarqa/products/gcov.py, src/nisarqa/products/gslc.py, src/nisarqa/products/igram.py, src/nisarqa/products/offsets.py, src/nisarqa/products/product_reader.py, src/nisarqa/products/rslc.py, src/nisarqa/utils/metadata_checks.py, src/nisarqa/utils/summary_csv.py, src/nisarqa/utils/typing.py
Previously, for RSLC, GSLC, and GCOV products, all metadata datasets under the `../metadata/calibrationInformation/` Group were incorrectly being referred to as "metadata cubes".
This is noted in the original QA repo's Issues #188 and #183, and arose again during NISAR I&T's R4.0.4 testing.
This PR addresses the problem in a few ways:
* Updates the terminology from "cube" to "dataset" in most places.
* Modularizes the `verify_metadata_cubes()` function into two distinct functions:
1) `verify_metadata_cubes()` for all L1/L2 products, which only checks the metadata cubes under the `radarGrid` or `geolocationGrid` Group
2) `verify_calibration_metadata()` which is only for non-InSAR products (RSLC, GSLC, GCOV), which specifically handles metadata under the …
=> Bugfix: Correct error messages for poorly-formed `calibrationInformation` metadata

src/nisarqa/utils/sanity_checks.py
Currently, QA assumes that all L1 and L2 products contain a boolean dataset `../identification/isJointObservation`.
That is true for the single-input products (RSLC, GSLC, GCOV). But for InSAR, this needs to be split into [`../identification/referenceIsJointObservation`](https://github-fn.jpl.nasa.gov/NISAR-ADT/NISAR_PIX/blob/f9a912736432837ba3d05494c0b45cdefe69288a/XML/L2/nisar_L2_GUNW.xml#L35) and [`../identification/secondaryIsJointObservation`](https://github-fn.jpl.nasa.gov/NISAR-ADT/NISAR_PIX/blob/f9a912736432837ba3d05494c0b45cdefe69288a/XML/L2/nisar_L2_GUNW.xml#L41).
This discrepancy is causing a false error to be written in the InSAR QA log file. This PR address that bug.
=> Bugfix: Update `isJointObservation` check for InSAR products

src/nisarqa/products/product_reader.py
For historical reasons, the InSAR product reader had a dtype check built into it. This check required that the QA developer know apriori the dtype of each dataset, and maintain the QA code if/when the product spec changed. This check in the product reader was intended to be a stop-gap, to be used until the actual QA XML checker was implemented and could algorithmically check the dtypes in the HDF5 file against the actual XML product specs for all datasets. That way, if/when the product spec XMLs are updated, then QA would get that update "for free".
The QA XML checker has since been implemented, and the XML vs. HDF5 dtypes are now being checked via [this function](https://github.com/isce-framework/nisarqa/blob/90dbb9e76442eda6dc34d8ed76f2225187ee22c4/src/nisarqa/utils/file_verification/che …
=> Bugfix: Remove InSAR dtype check in product reader

src/nisarqa/products/product_reader.py
In PR #14 , we removed the dtype checking for InSAR products in the product reader classes; the XML Checker rendered those checks no longer necessary, and buggy to maintain. The goal of this PR is to similarly removes the dtype checks in the RSLC, GSLC, and GCOV product readers.
Worth discussing is a proposed design change for the location of the `_get_dataset_handle()` function. Note: This function is only used during construction of the large *Raster classes for the imagery datasets. It doesn't get used by QA when accessing the tiny metadata datasets nor LUTs.
Previously, because RSLC, GSLC, and GCOV each expected different dtypes for the large imagery datasets, and because those dtypes changed over time, then `_get_dataset_handle()` was used to customize that function for each …
=> Remove dtype checking for RSLC, GSLC, GCOV in product reader classes

src/nisarqa/products/rslc.py
There is an extraneous context manager in the function `process_backscatter_imgs_and_browse()`. This PR removes that context manager.
=> Bugfix: Remove extraneous context manager

src/nisarqa/__init__.py, src/nisarqa/parameters/nisar_params.py, src/nisarqa/products/product_reader.py, src/nisarqa/utils/metadata_checks.py, src/nisarqa/utils/sanity_checks.py, src/nisarqa/utils/utils.py
This PR puts QA's `typing.py` module to its own public submodule, as suggested and reasoned in: https://github.com/isce-framework/nisarqa/pull/21#discussion_r2047657578 .
=> Move `typing.py` module to its own public submodule

src/nisarqa/utils/calc.py, src/nisarqa/utils/plotting.py
Two bugs were identified when running QA on RUNW and GUNW products generated from REE "noise" data, which resulted in RUNW and GUNW products without any connected components and which resulted in layers containing all ~0.0 values.
1) Bug: Exceptions raised when computing Connected Components metrics when there are no connected components.
- Fix: In `src/nisarqa/utils/calc.py`, default values are now set for this edge case
2) Bug: Exception raised when the pixel values imagery portion of a layer are constant (e.g. all ~0.0).
- Fix: Log a warning, but do not raise an exception. If a layer's pixels' values are approx. constant, it should be plotted.
- Note: There are some cases where a layer is known to be all ~zero-valued. There are existing QA checks to handle these cases.
=> Bugfix: Connected Components metrics and colorbar interval

.pre-commit-config.yaml, pyproject.toml, src/nisarqa/__init__.py, src/nisarqa/__main__.py, src/nisarqa/parameters/constants/globals.py, src/nisarqa/parameters/gcov_params.py, src/nisarqa/parameters/gslc_params.py, src/nisarqa/parameters/insar_params.py, src/nisarqa/parameters/nisar_params.py, src/nisarqa/parameters/rslc_caltools_params.py, src/nisarqa/products/caltools.py, src/nisarqa/products/gcov.py, src/nisarqa/products/gslc.py, src/nisarqa/products/igram.py, src/nisarqa/products/offsets.py, src/nisarqa/products/product_reader.py, src/nisarqa/products/rslc.py, src/nisarqa/utils/calc.py, src/nisarqa/utils/input_verification.py, src/nisarqa/utils/metadata_checks.py, src/nisarqa/utils/raster_classes.py, src/nisarqa/utils/sanity_checks.py, src/nisarqa/utils/stats_h5_writer/metrics_writer.py, src/nisarqa/utils/summary_csv.py, src/nisarqa/utils/tiling.py, src/nisarqa/utils/utils.py
Previously, all QA workflows read imagery Datasets directly from input HDF5 file for every feature. For example, after RSLC et al updated the baseline storage format for the imagery Datasets from uncompressed complex float16 to compressed complex float32, the QA runtime for RSLC increased from ~3-4min to ~10-15min for large Datasets.
The primary purpose of this PR is to `memmap` the primary imagery datasets one time (for the first read) and then store/access that memmap for subsequent reads. This enables significant speedup of processing, bringing the total runtime for RSLC compressed complex float32 datasets down to ~3min.
GSLC and GCOV use similar QA code as RSLC, so with minimal extra code in this PR, we should see speedup for them "for free".
The other significant addition to this PR …
=> Speedup: Add `memmap` cache for RSLC, GSLC, GCOV

src/nisarqa/parameters/nisar_params.py, src/nisarqa/parameters/rslc_caltools_params.py, src/nisarqa/products/gcov.py, src/nisarqa/products/gslc.py, src/nisarqa/products/igram.py, src/nisarqa/products/offsets.py, src/nisarqa/products/product_reader.py, src/nisarqa/products/rslc.py, src/nisarqa/utils/file_verification/checks.py, src/nisarqa/utils/plotting.py, src/nisarqa/utils/stats_h5_writer/setup_writer.py, src/nisarqa/utils/stats_h5_writer/stats_h5_globals.py, src/nisarqa/utils/utils.py
Closes https://github.com/isce-framework/nisarqa/issues/30. This PR copies the input granule's `runConfigurationContents` Dataset's contents for all L1/L2 product types.
This Dataset is copied into a new Group called `sourceData`, like this:
The name `sourceData` was chosen to stay in alignment with GSLC and GCOV, which nest copies of source data metadata under a similarly named Group. For example: `/science/LSAR/GCOV/metadata/sourceData/processingInformation/parameters/runConfigurationContents`
Because this is common functionality for all L1/L2, this PR takes the opportunity to refactor all of the `verify_*` functions, and collect all of these common setup functions under one new function called `setup_stats_h5_all_products()`.
=> Copy input granule's `runConfigurationContents`. Modularize `STATS.h5` setup.

src/nisarqa/utils/plotting.py
When creating the `boundaries` values to generate the discrete colorbar for the Connected Components plot, an integer overflow is occurring when using NumPy 2.0. This PR handles that bug.
h/t @gmgunter for identifying the underlying cause:
```
Yeah this changed in NumPy 2.0. It wasn't a bug in older NumPy versions -- the datatype would automatically be promoted to avoid overflow.
[1] https://numpy.org/doc/stable/numpy_2_0_migration_guide.html#changes-to-numpy-data-type-promotion
[2] https://numpy.org/neps/nep-0050-scalar-promotion.html
```
=> Bugfix for NumPy 2.0: Integer overflow for Connected Components labels

src/nisarqa/input_product_readers/geo_product.py, src/nisarqa/processing/setup_pdf.py, src/nisarqa/raster_classes.py
Closes #29 and #28 .
This PR:
* Adds the ESPG code to the PDF cover page for all L2 products
* Adds the EPSG code to the axes labels for all plots of L2 raster layers
* Updates "Northing" and "Easting" plot labels to the generic "Y Coordinate" and "X Coordinate" labels. These are generic for any EPSG code.
Note: the implementation in this PR is a very simple way to ensure that 1) all L2 PDF reports are correctly and consistently labeled, and 2) that this code can be reviewed and merged in time for R5.
After R5, if we have more time and would like to refine the placement of the EPSG code in each of the individual plots, let's revisit this issue at that time.
Attached is a GCOV PDF output, and here are screenshots of that report:
[REPORT.pdf](https://github.com/user-attachments/files/2176102 …
=> Add EPSG Code to L2 plots; Make L2 axes labels generic

src/nisarqa/validate/sanity_checks.py
After discussion with NISAR ADT, "Undefined" was removed from the list of options for `processingType`. This PR reflects that change.
For reference, here are the updates in the PIX product specs and ISCE3:
* (internal-only) https://github-fn.jpl.nasa.gov/NISAR-ADT/NISAR_PIX/pull/310
* RSLC: "Undefined" was never implemented
* Update in GSLC/GCOV: https://github.com/isce-framework/isce3/pull/59
* Update in InSAR: https://github.com/isce-framework/isce3/pull/60
=> Remove 'Undefined' from options for `processingType` validation checks

src/nisarqa/processing/stats_h5_writer/setup_writer.py, src/nisarqa/workflows/rslc_qa.py
Follow-on to #38, where there must have been a incorrectly-resolved merge conflict.
In brief, QA is trying to copy the `rfiLikelihood` Datasets from the input RSLC HDF5 to the QA STATS HDF5 **twice**.
It is using `copy_rfi_metadata_to_stats_h5()` to copy `rfiLikelihood` inside these functions:
* `rslc_qa()`
* `setup_stats_h5_non_insar_products()` (which is called directly inside `rslc_qa()`)
This was not detected previously due to a `try..except` block treating all `RuntimeError` the same; this allowed the QA bug to be quietly logged in the log file.
In this PR, we:
* Remove the redundant call to `copy_rfi_metadata_to_stats_h5()`
* Make the `try..except` specific to the error messages
=> Bugfix: Copy `rfilikelihood` correctly for RSLC

src/nisarqa/utils/input_verification.py, src/nisarqa/validate/sanity_checks.py
This PR updates and adds "sanity checks" to confirm that Datasets in the `identification` Group are correctly formed. Previously, most of these were simply not checked, with a "warning" logged saying that they were not checked. Now, they have more-robust checking.
Updates include:
* `compositeReleaseId` -> New function to check the correct number of digits and pattern
* `missionId` and `platformName` must each be "NISAR"
* `processingCenter` should be "JPL" or "ISRO"
* `instrumentName` should be "L-SAR" or "S-SAR"
* `productDoi` must follow ISO conventions
* `listOfObservationModes` -> each mode must follow a specific format
- Format determined per #57 
* `listOfFrequencies` must be a subset of {"A", "B"}
New Additions
* `plannedDatatakeId` and `plannedObservationId` are added for …
=> Add'l `identification` Group sanity checks

src/nisarqa/validate/sanity_checks.py
The `staticLayersDataAccess` metadata for L2 products was moved to the `identification` Group in product specs v1.4.0. This PR reflects that change.
=> Add sanity check for `staticLayersDataAccess`

src/nisarqa/parameters/insar_params.py, src/nisarqa/processing/insar/ionosphere_phase_screen.py
Per @oberonia78 , Based on the several discussions with InSAR team including @hfattahi , the `ionospherePhaseScreen` layer could be all NaN if there are no quality coherence values on the interferograms (e.g. the coherence is all very low).
To account for this expected case, this PR:
* Sets the RUNW and GUNW runconfig defaults to not fail if that layer is all-NaN values
* Updates the plotting code to not fail if that layer is all-NaN values
Note: Per @oberonia78 , `ionospherePhaseScreenUncentainty` will always have some values; we are only concerned with the `ionospherePhaseScreen`  in this update.
This PR was tested with both RUNW and GUNW products that have all-NaN values in the `ionospherePhaseScreen` layer.
cc: @vbrancat 
Comments:
1) With this PR, in the case of an all-NaN raster, QA …
=> Allow RUNW/GUNW `ionospherePhaseScreen` raster to be all NaN

src/nisarqa/raster_classes.py
For NumPy's `asarray()` function, the [`copy` parameter](https://numpy.org/doc/2.0/reference/generated/numpy.asarray.html#numpy-asarray) was added in NumPy 2.0.
Because ISCE3 builds with [NumPy 1.26.4](https://github.com/isce-framework/isce3/blob/ed73d7c48c8614e5a9ac836df95b999a535fb5d2/tools/imagesets/oracle8conda/runtime/spec-file.txt#L177), we need update QA to support this older NumPy version.
=> Bugfix: Support NumPy 1.26.4

src/nisarqa/parameters/nisar_params.py, src/nisarqa/processing/stats_h5_writer/setup_writer.py
This small, low-priority PR does the following:
- Fixes a small typo in the description of the `science/*SAR/sourceData/runConfigurationContents` dataset
- Clarifies that the `science/*SAR/QA/processing/runConfigurationContents` dataset was used for QA processing.
- While the path to this dataset could be used to infer its purpose, this small redundancy could clear up any residual confusion that a first-time viewer might encounter when looking over the file.
=> Tiny runConfigParameters dataset description changes
